import React from "react"
import { Img } from "react-image"
import RemoveCircleOutlineIcon from "@mui/icons-material/RemoveCircleOutline"
import AddCircleOutlineIcon from "@mui/icons-material/AddCircleOutline"
export { default as ErrorIcon } from "@mui/icons-material/Error"
export { default as CloseIcon } from "@mui/icons-material/Close"
export { default as SearchIcon } from "@mui/icons-material/FindReplace"
export { default as LookupIcon } from "@mui/icons-material/Search"
export { default as LaunchIcon } from "@mui/icons-material/Launch"
export { default as InfoIcon } from "@mui/icons-material/Info"
export { default as InfoOutlinedIcon } from "@mui/icons-material/InfoOutlined"
export { default as SettingsIcon } from "@mui/icons-material/Settings"
export { default as VisibilityIcon } from "@mui/icons-material/Visibility"
export { default as VisibilityOffIcon } from "@mui/icons-material/VisibilityOff"
export { default as EditIcon } from "@mui/icons-material/Edit"
export { default as KeyboardIcon } from "@mui/icons-material/Keyboard"
export { default as Label } from "@mui/icons-material/More"
export { default as HelpIcon } from "@mui/icons-material/Help"
export { default as ContentPasteIcon } from "@mui/icons-material/AssignmentReturned"
export { default as MDIcon } from "@mui/icons-material/FormatBold"

export const AddIcon = AddCircleOutlineIcon
export const RemoveIcon = RemoveCircleOutlineIcon
